apiVersion: v1
kind: Pod
metadata:
  name: kuard-a
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard-a
      resources:
        requests:
          cpu: "300m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard-b
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard-b
      resources:
        requests:
          cpu: "300m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard-c
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard-c
      resources:
        requests:
          cpu: "300m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
