apiVersion: v1
kind: Pod
metadata:
  name: kuard-a
spec:
  volumes:
    - name: "kuard-data"
      nfs:
        server: ks1
        path: "/var/export"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard-a
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      resources:
        requests:
          cpu: "600m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
